# USERNAME            =   "//android.widget.EditText[@hint=\"Nom d'utilisateur\"]"
# PASSWORD            =   "//android.widget.EditText[@hint=\"Mot de passe\"]"
# LOGIN               =   "accessibility_id=Se connecter"
# PAGE_FORM           =   "//android.view.View[@content-desc=\"Ajouter un produit\"]"
# PAGE_LIST_PROUDCTS  =   "//android.view.View[@content-desc=\"Liste des produits\"]"

# # FORM ELEMENTS
# FORM_TITLE           =   "//android.widget.EditText[@hint=\"Titre\"]"
# FORM_PRICE          =   "//android.widget.EditText[@hint=\"Prix\"]"
# FORM_DESCRIPTION    =   "//android.widget.EditText[@hint=\"Description\"]"
# FORM_CATEGORIE      =   "//android.widget.EditText[@hint=\"Catégorie\"]"
# FORM_URL            =   "//android.widget.EditText[@hint=\"Image URL\"]"
# FORM_BUTTON_ADD     =   "//android.widget.Button[@content-desc=\"Ajouter\"]"

# PRODUCT=   "accessibility_id=Rain Jacket Women Windbreaker Striped Climbing Raincoats\n39.99 $"

USERNAME           =   "android=new UiSelector().className(\"android.widget.EditText\").instance(0)"
PASSWORD           =   "android=new UiSelector().className(\"android.widget.EditText\").instance(1)"
LOGIN           =   "android=new UiSelector().description(\"Se connecter\")"
PAGE_FORM          =   "android=new UiSelector().description(\"Ajouter un produit\")"
PAGE_LIST_PROUDCTS  =   "android=new UiSelector().description(\"Liste des produits\")"
FORM_TITLE         =   "android=new UiSelector().className(\"android.widget.EditText\").instance(0)"
FORM_PRICE         =   "android=new UiSelector().className(\"android.widget.EditText\").instance(1)"
FORM_DESCRIPTION   =   "android=new UiSelector().className(\"android.widget.EditText\").instance(2)"
FORM_CATEGORIE     =   "android=new UiSelector().className(\"android.widget.EditText\").instance(3)"
FORM_URL           =   "android=new UiSelector().className(\"android.widget.EditText\").instance(4)"
FORM_BUTTON_ADD    =   "android=new UiSelector().description(\"Ajouter\")"
PRODUCT        =   "android=new UiSelector().description(\"Mens Cotton Jacket\n55.99 $\")"